@startuml genetic-algorythm
title Блок-схема Генетического Алгоритма

start
:Инициализация топологии сети;
:Инициализация параметров;
:Генерация начальной популяции;

while (Условие остановки достигнуто?) is (Нет)
    :       Вычисление функции 
    пригодности для каждой особи;
    note right
    оценить качество решений 
    (особей), представленных 
    в виде хромосом, и определить, 
    насколько они соответствуют 
    решаемой задаче. 
    end note

    :Селекция;
    note left
    Селекция выбирает наиболее 
    приспособленные особи для 
    воспроизведения на основе 
    их пригодности.
    end note

    :Оператор кроссовера;
    note right
    Кроссовер объединяет 
    части двух родителей, 
    создавая новое потомство.
    end note

    :Оператор мутации;
    note left
    Мутация вносит случайные
    изменения в особи для 
    поддержания разнообразия
    в популяции.
    end note

    :Добавление особи 
    в новое поколение;
endwhile

:Завершение алгоритма;
stop

@enduml